"""Anima LoRA Trainer ComfyUI node.

A single, deliberately small node: feed it one IMAGE + a caption, pick the base
Anima checkpoint, a rank, an epoch count and a GPU tier, and on launch it trains
a T-LoRA + OrthoLoRA against that one image/prompt pair.

Design notes:

- **No MODEL input.** Holding the base DiT resident in ComfyUI *and* spawning a
  training subprocess on the same GPU is an easy OOM. So this node does not take
  a MODEL socket; instead it loads the chosen Anima checkpoint itself **after**
  training finishes and returns a patched MODEL — a drop-in for
  ``UNETLoader → Anima Adapter Loader``.
- **Daemon required.** Training always runs in the local training daemon's own
  detached subprocess (out of the ComfyUI process). If the daemon isn't up this
  node errors out rather than auto-starting it.
"""

from __future__ import annotations

import datetime as _dt
import importlib
import os
import sys

import folder_paths  # ComfyUI builtin

# Training deps are imported lazily inside `train()` so that merely loading this
# module in ComfyUI doesn't force `library.*` imports (which pull torch
# extensions and slow startup).


# ---------------------------------------------------------------------------
# Discovery helpers
# ---------------------------------------------------------------------------


def _anima_lora_root() -> str:
    from .training import find_anima_lora_root

    return find_anima_lora_root(os.path.dirname(__file__))


def _comfy_loras_dir() -> str:
    """Return the first directory registered under ComfyUI's 'loras' folder."""
    entry = folder_paths.folder_names_and_paths.get("loras")
    if not entry or not entry[0]:
        raise RuntimeError("ComfyUI has no 'loras' folder registered.")
    return entry[0][0]


def _resolve_daemon_client():
    """Return the ``DaemonClient`` class, live-or-vendor.

    Mirrors the live-or-vendor pattern in the sibling nodes (see
    ``comfyui-hydralora/adapter.py``). Two install shapes:

    1. **Inside anima_lora** — the live ``scripts.daemon.client`` is reachable;
       it resolves the daemon port from the repo's pidfile, so it follows a
       daemon that bound a fallback port.
    2. **Standalone** (this folder dropped into ``ComfyUI/custom_nodes/``) —
       falls back to the pure-stdlib client under ``_vendor/`` (regenerated by
       ``scripts/sync_vendor.py``). With no repo pidfile to read it talks to the
       default port (``127.0.0.1:8765``; override with ``ANIMA_DAEMON_PORT``).

    Either way the client only *talks* to a daemon — it never starts one, so
    the anima_lora repo + its daemon must be running on this machine.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(here, "..", ".."))
    vendor = os.path.join(here, "_vendor")
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    try:
        mod = importlib.import_module("scripts.daemon.client")
    except ImportError:
        if not os.path.isdir(vendor):
            raise
        if vendor not in sys.path:
            sys.path.insert(0, vendor)
        mod = importlib.import_module("scripts.daemon.client")
    return mod.DaemonClient


def _trainer_tmp_root() -> str:
    """Where single-image-mode datasets are staged before submission.

    Prefers the repo's ``output/tmp_trainer`` (so it's covered by the repo
    gitignore and easy to prune), but falls back to ComfyUI's temp dir when the
    node is installed outside the anima_lora tree — the daemon reads it over a
    plain filesystem path either way (same machine, localhost-only).
    """
    try:
        return os.path.join(_anima_lora_root(), "output", "tmp_trainer")
    except Exception:
        return os.path.join(folder_paths.get_temp_directory(), "anima_trainer")


# ---------------------------------------------------------------------------
# Train via daemon → block until done → return saved safetensors path
# ---------------------------------------------------------------------------


def _train_and_save(
    *,
    method: str,
    preset: str,
    overrides: dict,
    image,
    prompt: str,
) -> str:
    """Submit single-image training to the local daemon and block until done.

    The daemon runs ``accelerate launch … train.py`` in its **own** detached
    subprocess, so a CUDA OOM / segfault kills only the job — not ComfyUI. This
    call polls ``GET /jobs/{id}`` and drives a ``ProgressBar`` until the job
    reaches a terminal state, then returns the absolute path of the saved
    safetensors.

    Raises ``RuntimeError`` if the daemon is not already running — this node
    does not auto-start it.
    """
    import time

    import comfy.model_management
    import comfy.utils

    from .dataset_prep import prepare_dataset_dir

    # Daemon must already be up. We do NOT auto-start it here.
    DaemonClient = _resolve_daemon_client()
    client = DaemonClient()
    if client.health() is None:
        raise RuntimeError(
            "Anima training daemon is not running. Start it with `make daemon` "
            "(or `python tasks.py daemon`) from the anima_lora/ directory, then "
            "re-run this node."
        )

    # dataset_dir="" → single-image mode (writes the IMAGE batch + caption sidecars).
    work_dir, dataset_cfg, n_images = prepare_dataset_dir(
        image, prompt, "", tmp_root=_trainer_tmp_root()
    )

    ts = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_name = f"anima_trainer_{ts}"
    output_dir = _comfy_loras_dir()

    overrides = dict(overrides)
    overrides.setdefault("dataset_config", dataset_cfg)
    overrides.setdefault("output_dir", output_dir)
    overrides.setdefault("output_name", output_name)

    print(
        f"[Anima Trainer] submitting method={method} preset={preset} "
        f"images={n_images} → {output_name}.safetensors",
        flush=True,
    )

    # Free ComfyUI-held VRAM so the (separate) training process has room for its
    # own DiT + optimizer state. The daemon spawns the job; we just watch.
    comfy.model_management.unload_all_models()
    try:
        import gc

        import torch

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass

    job_id = client.submit(
        method=method,
        preset=preset,
        methods_subdir="gui-methods",
        overrides=overrides,
    )["job_id"]
    print(f"[Anima Trainer] queued as job {job_id}", flush=True)

    expected = os.path.join(output_dir, f"{output_name}.safetensors")
    pbar = None
    total = None
    last_state = None
    while True:
        try:
            job = client.get(job_id)
        except Exception as e:  # daemon hiccup — keep polling briefly
            print(f"[Anima Trainer] poll error: {e}", flush=True)
            time.sleep(2.0)
            continue

        state = job.get("state")
        if state != last_state:
            print(f"[Anima Trainer] job {job_id}: {state}", flush=True)
            last_state = state

        latest = job.get("latest") or {}
        if total is None:
            total = _read_total_steps(job.get("progress_path"))
            if total:
                pbar = comfy.utils.ProgressBar(total)
        step = latest.get("global_step")
        if pbar is not None and isinstance(step, int):
            pbar.update_absolute(min(step, total), total)

        if state in ("done", "error", "stopped"):
            break
        time.sleep(1.5)

    if state == "done":
        path = expected if os.path.exists(expected) else job.get("ckpt_path")
        if not path or not os.path.exists(path):
            raise RuntimeError(
                f"Training finished but no checkpoint found (expected {expected}). "
                f"See the job stdout log: {job.get('stdout_path')}"
            )
        print(f"[Anima Trainer] saved {path}", flush=True)
        return path

    raise RuntimeError(
        f"Training job {job_id} ended as '{state}': {job.get('error') or '(no detail)'}. "
        f"See the job stdout log: {job.get('stdout_path')}"
    )


def _read_total_steps(progress_path) -> int | None:
    """Read ``total_steps`` from the run_start line of a job's progress.jsonl.

    The daemon and ComfyUI share a machine, so reading the local file is the
    cheapest way to size the progress bar without bloating the HTTP API.
    """
    if not progress_path or not os.path.isfile(progress_path):
        return None
    try:
        import json

        with open(progress_path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if '"run_start"' not in line:
                    continue
                rec = json.loads(line)
                if rec.get("ev") == "run_start":
                    val = rec.get("total_steps")
                    return int(val) if val else None
    except (OSError, ValueError):
        return None
    return None


def _load_anima_model(anima_model: str):
    """Load a base Anima DiT from ComfyUI's diffusion_models folder as a MODEL.

    Replicates ComfyUI's ``UNETLoader.load_unet`` (default weight dtype) so the
    returned object is a normal ``ModelPatcher`` — identical to what the user
    would get by chaining a UNETLoader.
    """
    import comfy.sd

    unet_path = folder_paths.get_full_path_or_raise("diffusion_models", anima_model)
    return comfy.sd.load_diffusion_model(unet_path, model_options={})


def _apply_lora_to_model(model, file_path: str, strength: float) -> None:
    """Apply an anima-family adapter (LoRA / Hydra / ReFT) to a MODEL.

    Delegates to the sibling ``comfyui-hydralora`` custom node for the actual
    patching so there is one source of truth for key-sniffing + hook install.
    """
    try:
        from custom_nodes.comfyui_hydralora.adapter import apply_adapter
    except ImportError:
        # ComfyUI registers custom nodes under hyphenated dir names; the
        # hyphen→underscore module alias is not automatic. Fall back to a direct
        # path import of the sibling node.
        import importlib.util

        sibling = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "comfyui-hydralora",
            "adapter.py",
        )
        if not os.path.exists(sibling):
            raise RuntimeError(
                "Cannot apply adapter: sibling `comfyui-hydralora/adapter.py` "
                f"not found at {sibling}. Install that custom node alongside "
                "this one, or load the resulting LoRA manually."
            )
        spec = importlib.util.spec_from_file_location("_anima_trainer_adapter", sibling)
        mod = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(mod)
        apply_adapter = mod.apply_adapter
    apply_adapter(model, file_path, strength, strength)


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------


class AnimaLoRATrainer:
    """Train an Anima LoRA (T-LoRA + OrthoLoRA) from one image + caption.

    Loads the chosen base checkpoint itself after training and returns a patched
    MODEL — use it exactly like the output of an Anima Adapter Loader.
    """

    @classmethod
    def INPUT_TYPES(cls):
        unets = folder_paths.get_filename_list("diffusion_models") or [""]
        return {
            "required": {
                "anima_model": (
                    unets,
                    {
                        "tooltip": (
                            "Base Anima DiT checkpoint (ComfyUI diffusion_models "
                            "folder). Used for training and reloaded afterwards to "
                            "produce the output MODEL."
                        )
                    },
                ),
                "image": ("IMAGE", {"tooltip": "The image(s) to train on."}),
                "text": (
                    "STRING",
                    {
                        "default": "",
                        "multiline": True,
                        "tooltip": "Caption for the training image.",
                    },
                ),
                "rank": (
                    "INT",
                    {
                        "default": 16,
                        "min": 1,
                        "max": 256,
                        "tooltip": "LoRA rank (network_dim); alpha is tied to it.",
                    },
                ),
                "epochs": (
                    "INT",
                    {"default": 25, "min": 1, "max": 10000},
                ),
                "gpu": (["8GB", "16GB", "high"], {"default": "16GB"}),
            },
        }

    RETURN_TYPES = ("MODEL",)
    RETURN_NAMES = ("model",)
    FUNCTION = "train"
    CATEGORY = "anima/training"
    DESCRIPTION = (
        "Train an Anima T-LoRA + OrthoLoRA from a single image + caption, then "
        "load the chosen base checkpoint and return it with the trained LoRA "
        "applied — a drop-in for the Anima Adapter Loader's MODEL output. "
        "Training runs in the local Anima daemon (errors if the daemon isn't "
        "running); the UI stays responsive and a progress bar tracks the run."
    )

    def train(
        self,
        anima_model: str,
        image,
        text: str,
        rank: int,
        epochs: int,
        gpu: str,
    ):
        from .training import GPU_TIER_PRESET, gpu_tier_overrides

        anima_path = folder_paths.get_full_path_or_raise(
            "diffusion_models", anima_model
        )

        overrides: dict = {
            "network_dim": int(rank),
            "network_alpha": float(rank),
            "max_train_epochs": int(epochs),
            # Train against the user-selected base checkpoint.
            "pretrained_model_name_or_path": anima_path,
        }
        overrides.update(gpu_tier_overrides(gpu))

        saved_path = _train_and_save(
            method="tlora",
            preset=GPU_TIER_PRESET[gpu],
            overrides=overrides,
            image=image,
            prompt=text,
        )

        # Load the base DiT ourselves (avoids holding it resident during the run)
        # and return it patched — a drop-in for the Anima Adapter Loader.
        model = _load_anima_model(anima_model)
        _apply_lora_to_model(model, saved_path, 1.0)
        return (model,)


NODE_CLASS_MAPPINGS = {
    "AnimaLoRATrainer": AnimaLoRATrainer,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaLoRATrainer": "Anima LoRA Trainer",
}
